# 1. Part 1 - Joins

In [1]:
import pandas as pd
from IPython.display import display

# Sample DataFrames
df1 = pd.DataFrame({'key': ['A', 'B', 'C', 'D'],
                    'value': [1, 2, 3, 4]})
df2 = pd.DataFrame({'key': ['C', 'D', 'E', 'F'],
                    'value': [3, 4, 5, 6]})

# Inner Join
inner_joined = df1.merge(df2, on='key', how='inner', suffixes=('_left', '_right'))
display(inner_joined)

# Left Join
left_joined = df1.merge(df2, on='key', how='left', suffixes=('_df1', '_df2'))
print("\nLeft Join:")
display(left_joined)

# Right Join
right_joined = df1.merge(df2, on='key', how='right', suffixes=('_df1', '_df2'))
print("\nRight Join:")
display(right_joined)

# Outer Join
outer_joined = df1.merge(df2, on='key', how='outer', suffixes=('_df1', '_df2'))
print("\nOuter Join:")
display(outer_joined)

  key  value_left  value_right
0   C           3            3
1   D           4            4

Left Join:

  key  value_df1  value_df2
0   A          1        NaN
1   B          2        NaN
2   C          3        3.0
3   D          4        4.0

Right Join:

  key  value_df1  value_df2
0   C        3.0          3
1   D        4.0          4
2   E        NaN          5
3   F        NaN          6

Outer Join:

  key  value_df1  value_df2
0   A        1.0        NaN
1   B        2.0        NaN
2   C        3.0        3.0
3   D        4.0        4.0
4   E        NaN        5.0
5   F        NaN        6.0

In [2]:
# There are situations where you might want to concatenate DataFrames vertically or horizontally
concatenated = pd.concat([df1, df2], axis=0)  # Vertically
print("\nConcatenated:")
display(concatenated)

Concatenated:

  key  value
0   A      1
1   B      2
2   C      3
3   D      4
0   C      3
1   D      4
2   E      5
3   F      6

In [3]:
# Joining can also be performed based on indices
joined_on_index = df1.join(df2, lsuffix='_left', rsuffix='_right')
print("\nJoin on index:")
display(joined_on_index)

Join on index:

  key_left  value_left key_right  value_right
0        A           1         C            3
1        B           2         D            4
2        C           3         E            5
3        D           4         F            6

# Part 2 - Data Cleaning

## String operations

- Strings are sequences of characters.
- Defined using single, double, or triple quotes ('hello', "hello", '''hello''').

### Common operations

In [4]:
# Concatenation: Combine strings.
greeting = "Hello" + " " + "World"

# Length: len(string) returns the number of characters.
length = len("Hello")

# Indexing: Access individual characters.
first_char = "Hello"[0]  # Returns 'H'

# Slicing: Extract portions of a string.
slice_string = "Hello"[1:4]  # Returns 'ell'

# Methods: Strings come with built-in methods.
"hello".upper()  # Returns 'HELLO'
"HELLO".lower()  # Returns 'hello'
"hello world".split()  # Returns ['hello', 'world']
"  hello  ".strip()    # Returns 'hello'

'hello'

### Formatting

In [5]:
# Using the % operator.
print("Hello %s" % "World")

# Using the str.format() method.
print("Hello {}".format("World"))

# f-strings in Python 3.6+.
world = "World"
print(f"Hello {world}")

Hello World
Hello World
Hello World

### Pandas string operations

In [6]:
import pandas as pd
s = pd.Series(['hello', 'world', None, 'example'])
capitalized = s.str.capitalize()
capitalized

0      Hello
1      World
2       None
3    Example
dtype: object

In [7]:
# lower(), upper(), title(), capitalize(): Change the case.
s.str.upper()

0      HELLO
1      WORLD
2       None
3    EXAMPLE
dtype: object

In [8]:
# len(): Compute string lengths.
s.str.len()

0    5.0
1    5.0
2    NaN
3    7.0
dtype: float64

In [9]:
# strip(), rstrip(), lstrip(): Remove whitespace.
s.str.strip()

0      hello
1      world
2       None
3    example
dtype: object

In [10]:
#startswith() and endswith(): Check if string starts or ends with a pattern.
s.str.startswith('he')

0     True
1    False
2     None
3    False
dtype: object

In [11]:
# contains(): Check if string contains a pattern.
s.str.contains('ex')

0    False
1    False
2     None
3     True
dtype: object

In [12]:
# split() and rsplit(): Split strings on delimiter.
s.str.split('e')

0       [h, llo]
1        [world]
2           None
3    [, xampl, ]
dtype: object

In [13]:
# replace(): Replace occurrences.
s.str.replace('hello', 'hi')

0         hi
1      world
2       None
3    example
dtype: object

In [14]:
# extract(): Extract groups from strings matching a regex pattern.
s.str.extract(r'(\w{3})')  # Extracts first three letters

     0
0  hel
1  wor
2  NaN
3  exa

In [15]:
# Handling Missing Data
s.str.contains('he', na=False)

0     True
1    False
2    False
3    False
dtype: bool

In [16]:
# Concatenate
s.str.cat(sep='-')

'hello-world-example'

### Data Cleaning

In [17]:
import pandas as pd
import numpy as np

# Create a DataFrame
data = {
    'Date': ['2023-09-01', '2023-09-01', '2023-09-02', '2023-09-02', '2023-09-03', '2023-09-04', '2023-09-05', '2023-09-05'],
    'Product_ID': [101, 102, 103, 104, 105, 106, 107, 108],
    'Product_Name': ['Laptop', 'Camera', 'Keyboard', 'Monitor', 'Tablet', 'Smartphone', 'Headset', 'Camera'],
    'Sales': [1000, 150, 200, 450, None, None, 150, 500],
    'Returns': [2, 5, 1, 0, 3, 2, 1, 1]
}

df = pd.DataFrame(data)

display(df)

         Date  Product_ID Product_Name   Sales  Returns
0  2023-09-01         101       Laptop  1000.0        2
1  2023-09-01         102       Camera   150.0        5
2  2023-09-02         103     Keyboard   200.0        1
3  2023-09-02         104      Monitor   450.0        0
4  2023-09-03         105       Tablet     NaN        3
5  2023-09-04         106   Smartphone     NaN        2
6  2023-09-05         107      Headset   150.0        1
7  2023-09-05         108       Camera   500.0        1

### 1. Handling Missing Data:

Data can have missing values for a variety of reasons, and handling them correctly is crucial.

Detect Missing Values: Use isna() or isnull() to detect missing values.

In [18]:
df.isna().sum()

Date            0
Product_ID      0
Product_Name    0
Sales           2
Returns         0
dtype: int64

- Filling Missing Data:

  - Fill with a constant: df.fillna(value)
  - Forward fill (propagate the last valid observation): df.fillna(method='ffill')
  - Backward fill: df.fillna(method='bfill')
  - Fill with mean, median, etc.: df.fillna(df.mean())

Dropping Missing Data: If you want to remove missing data.

In [19]:
df.dropna(axis=0)  # drops rows with NaN values
df.dropna(axis=1)  # drops columns with NaN values

         Date  Product_ID Product_Name  Returns
0  2023-09-01         101       Laptop        2
1  2023-09-01         102       Camera        5
2  2023-09-02         103     Keyboard        1
3  2023-09-02         104      Monitor        0
4  2023-09-03         105       Tablet        3
5  2023-09-04         106   Smartphone        2
6  2023-09-05         107      Headset        1
7  2023-09-05         108       Camera        1

### 2. Removing Duplicates:
Duplicate rows can skew your analysis.

In [20]:
# Detect duplicates:
df.duplicated()

# Remove duplicates:
df.drop_duplicates()

         Date  Product_ID Product_Name   Sales  Returns
0  2023-09-01         101       Laptop  1000.0        2
1  2023-09-01         102       Camera   150.0        5
2  2023-09-02         103     Keyboard   200.0        1
3  2023-09-02         104      Monitor   450.0        0
4  2023-09-03         105       Tablet     NaN        3
5  2023-09-04         106   Smartphone     NaN        2
6  2023-09-05         107      Headset   150.0        1
7  2023-09-05         108       Camera   500.0        1

### 3. Type Conversion:
Data types might not always be what you expect. You might need to convert between types.

In [21]:
'''
#Convert data type of a column:
df['column_name'] = df['column_name'].astype('new_type')

# Convert to datetime:
df['date_column'] = pd.to_datetime(df['date_column'])

# Categorical data conversion:
df['category_column'] = df['category_column'].astype('category')
'''

"\n#Convert data type of a column:\ndf['column_name'] = df['column_name'].astype('new_type')\n\n# Convert to datetime:\ndf['date_column'] = pd.to_datetime(df['date_column'])\n\n# Categorical data conversion:\ndf['category_column'] = df['category_column'].astype('category')\n"