In [135]:
#import all the necessary libraries
import pandas as pd
import seaborn as sns
import xml.etree.ElementTree as ET

In [136]:
def parse_xml(xml_file):
    tree = ET.parse(xml_file)
    root = tree.getroot()
    return root

def extract_data(root):
    data = []
    for record in root.findall('system'):
        row = {}
        for field in record:
            row[field.tag] = field.text
        data.append(row)
    return data

def to_dataframe(data):
    df = pd.DataFrame(data)
    return df

In [137]:
root = parse_xml('data/systems.xml')
data = extract_data(root)
df = to_dataframe(data)
#df = df.dropna()
df.head()

,name,rightascension,declination,distance,star,videolink,constellation,binary,spectraltype,planet,magJ,magH,magK
0,11 Com,12 20 43.0255,+17 47 34.3392,88.9,\n\t\t,http://youtu.be/qyJXJJDrEDo,Coma Berenices,NaN,NaN,NaN,NaN,NaN,NaN
1,11 UMi,15 17 05.88899,+71 49 26.0466,122.1,\n\t\t,NaN,Ursa Minor,NaN,NaN,NaN,NaN,NaN,NaN
2,14 And,23 31 17.41346,+39 14 10.3092,79.2,\n\t\t,NaN,Andromeda,NaN,NaN,NaN,NaN,NaN,NaN
3,14 Her,16 10 24.3152,+43 49 03.4987,18.1,\n\t\t,NaN,Hercules,NaN,NaN,NaN,NaN,NaN,NaN
4,16 Cygni,19 41 48.95343,+50 31 30.2153,21.146,NaN,NaN,Cygnus,\n\t\t,NaN,NaN,NaN,NaN,NaN

In [138]:
df.shape

(3891, 13)

In [139]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3891 entries, 0 to 3890
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            3891 non-null   object
 1   rightascension  3890 non-null   object
 2   declination     3890 non-null   object
 3   distance        3692 non-null   object
 4   star            3705 non-null   object
 5   videolink       30 non-null     object
 6   constellation   3890 non-null   object
 7   binary          181 non-null    object
 8   spectraltype    1 non-null      object
 9   planet          5 non-null      object
 10  magJ            2 non-null      object
 11  magH            2 non-null      object
 12  magK            2 non-null      object
dtypes: object(13)
memory usage: 395.3+ KB

In [140]:
df = df[['name','rightascension','declination', 'distance','star','constellation','planet']]

In [141]:
df.head()

,name,rightascension,declination,distance,star,constellation,planet
0,11 Com,12 20 43.0255,+17 47 34.3392,88.9,\n\t\t,Coma Berenices,NaN
1,11 UMi,15 17 05.88899,+71 49 26.0466,122.1,\n\t\t,Ursa Minor,NaN
2,14 And,23 31 17.41346,+39 14 10.3092,79.2,\n\t\t,Andromeda,NaN
3,14 Her,16 10 24.3152,+43 49 03.4987,18.1,\n\t\t,Hercules,NaN
4,16 Cygni,19 41 48.95343,+50 31 30.2153,21.146,NaN,Cygnus,NaN

In [142]:
#df.drop(columns=['planet', 'star'], inplace=True)
#df.dropna(inplace=True)

In [143]:
df.columns.tolist()

['name',
 'rightascension',
 'declination',
 'distance',
 'star',
 'constellation',
 'planet']

In [144]:
df.head(10)

,name,rightascension,declination,distance,star,constellation,planet
0,11 Com,12 20 43.0255,+17 47 34.3392,88.9,\n\t\t,Coma Berenices,NaN
1,11 UMi,15 17 05.88899,+71 49 26.0466,122.1,\n\t\t,Ursa Minor,NaN
2,14 And,23 31 17.41346,+39 14 10.3092,79.2,\n\t\t,Andromeda,NaN
3,14 Her,16 10 24.3152,+43 49 03.4987,18.1,\n\t\t,Hercules,NaN
4,16 Cygni,19 41 48.95343,+50 31 30.2153,21.146,NaN,Cygnus,NaN
5,18 Del,20 58 25.93397,+10 50 21.4289,75.3,\n\t\t,Delphinus,NaN
6,1RXS1609,16 09 30,-21 04 58,145,\n\t\t,Scorpius,NaN
7,1SWASP J1407,14 07 47.93,-39 45 42.7,133,\n\t\t,Centaurus,NaN
8,HIP 70791,14 28 37.8130,+49 50 41.4610,96.25,\n\t\t,Boötes,NaN
9,24 Sex,10 23 28.3693,-00 54 08.0771,74.8,\n\t\t,Sextans,NaN

In [145]:
sns.barplot(df, x=df.columns[0], y=df.columns[3])

C:\Java\Python3.10.8\lib\site-packages\seaborn\_decorators.py:36: FutureWarning: Pass the following variable as a keyword arg: x. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  warnings.warn(

ValueError: Could not interpret input 'distance'

In [ ]:
df['planet'].value_counts()

In [ ]:
df.info()

In [ ]:
import numpy as np
df.star.value_counts()

In [ ]:
df[df['planet']=='\n\t\t']['planet']